# Generated by Django 4.1.1 on 2022-11-13 09:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='session',
            new_name='sessionperiod',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_endexam_marks',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(70), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_exam1_marks',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject_exam2_marks',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='subjects',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.classes'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('name', 'sessionperiod')},
        ),
        migrations.AlterUniqueTogether(
            name='studentresult',
            unique_together={('student_id', 'subject_id')},
        ),
        migrations.CreateModel(
            name='LeaveReportStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_leave_date', models.CharField(max_length=255)),
                ('end_leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemapp.staffs')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_assignment_marks',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject_exam_marks',
        ),
    ]
