# Generated by Django 4.1.1 on 2022-12-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffs',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
