# Generated by Django 4.1.1 on 2022-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0002_rename_session_classes_sessionperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyearmodel',
            name='school_term',
            field=models.CharField(choices=[('First Term', 'First Term'), ('Second Term', 'Second Term'), ('Third Term', 'Third Term')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
