# Generated by Django 4.1.1 on 2022-11-13 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0003_sessionyearmodel_school_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='sessionperiod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.sessionyearmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionyearmodel',
            unique_together={('school_term', 'session_start_year', 'session_end_year')},
        ),
    ]
