# Generated by Django 4.1.1 on 2022-11-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0005_alter_students_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='students',
            name='subject_id',
            field=models.ManyToManyField(to='systemapp.subjects'),
        ),
    ]
