# Generated by Django 4.1.1 on 2022-11-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0006_remove_students_subject_id_students_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='national_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='staff_ID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
