# Generated by Django 4.1.1 on 2022-12-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0007_alter_studentresult_subject_endexam_marks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('mean_marks', models.IntegerField(blank=True, null=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemapp.students')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemapp.subjects')),
            ],
            options={
                'unique_together': {('student_id', 'subject_id')},
            },
        ),
        migrations.CreateModel(
            name='studentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('p_comments', models.CharField(blank=True, max_length=100, null=True)),
                ('t_comments', models.CharField(blank=True, max_length=100, null=True)),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('s_mean_marks', models.IntegerField(blank=True, null=True)),
                ('all_points', models.FloatField(blank=True, null=True)),
                ('all_subjects', models.ManyToManyField(to='systemapp.studentresult')),
                ('classes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_report', to='systemapp.classes')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_report', to='systemapp.students')),
            ],
            options={
                'unique_together': {('classes_id', 'student_id')},
            },
        ),
    ]
