# Generated by Django 4.1.1 on 2022-11-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0007_alter_staffs_national_id_alter_staffs_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='national_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='staff_ID',
            field=models.TextField(blank=True, null=True),
        ),
    ]
