# Generated by Django 4.1.1 on 2022-12-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0008_subjectinfo_studentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='classes_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='systemapp.classes'),
            preserve_default=False,
        ),
    ]
