# Generated by Django 4.1.1 on 2022-11-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0008_alter_admin_national_id_alter_admin_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='admitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='students',
            name='fathers_email',
            field=models.EmailField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='fathers_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='fathers_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='mothers_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='mothers_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='residential_address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
