# Generated by Django 4.1.1 on 2022-11-23 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0009_students_admitted_at_students_fathers_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='session_year_id',
        ),
        migrations.AddField(
            model_name='students',
            name='session_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.sessionyearmodel'),
        ),
    ]
