# Generated by Django 4.1.1 on 2022-12-23 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0009_studentresult_classes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentreport',
            name='sessionperiod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.sessionyearmodel'),
        ),
    ]
