# Generated by Django 4.1.1 on 2022-11-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0010_remove_students_session_year_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionyearmodel',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='mothers_email',
            field=models.EmailField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
