# Generated by Django 4.1.1 on 2022-11-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0012_rename_sessionperiod_classes_sessionperiod_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='session_year',
            new_name='session_year_id',
        ),
    ]
