# Generated by Django 4.1.1 on 2022-11-28 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0013_rename_session_year_students_session_year_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='sessionperiod_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='systemapp.sessionyearmodel'),
        ),
    ]
