# Generated by Django 4.1.1 on 2022-11-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systemapp', '0014_alter_classes_sessionperiod_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='sessionperiod_id',
            new_name='sessionperiod',
        ),
    ]
